### ISSUE TITLE
至尊研究院的多方块结构用不了

### ISSUE THREAD

**Issue by wadigzxc** [SlimefunGuguProject/SupremeExpansion#5]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [x] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [x] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/SupremeExpansion/issues)，且没有找到相同的问题

### 问题描述

至尊研究的多方块结构用不了，希望能解决至尊研究院合成至尊资源时不能用多方块结构合成的问题。

### 复现步骤

1.打开粘液科技指南
2.找到至尊研究院。
3.找到至尊资源里面的至尊圆石。
4.用至尊机器里面的岩心机，一种多方块结构机器合成错误。
![图片](https://user-images.githubusercontent.com/102936275/172044830-4b7cec14-136f-452f-937f-effd33aeec34.png)
![图片](https://user-images.githubusercontent.com/102936275/172044837-fcd3098c-1c6c-4fb6-810d-8a8e294926c0.png)

### 预期行为

想合成至尊研究院，至尊资源里的至尊圆石，但是不能用多方块结构合成，用电力合成是可以的。

### 服务端软件

Paper

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![图片](https://user-images.githubusercontent.com/102936275/172044633-131cd6a9-5957-4be9-8c0e-8b7c9e99a370.png)
![图片](https://user-images.githubusercontent.com/102936275/172044637-80fb4c42-3bd8-4955-930c-b4f70cfe1152.png)

### 插件版本

Slimefun-v2022.05-release.

**Comment by ybw0014** [comment]
该附属已更新至2.0，但我们还没有翻译新版本。暂时不会处理旧版本的问题。
